MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.16"                # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.16"                # [osx and x86_64]
c_compiler_version:    # [osx]
  - 14                 # [osx]
cxx_compiler_version:  # [osx]
  - 14                 # [osx]
