{% set name = "pyston_lite" %}
{% set pyston_version = "2.3.5" %}

package:
  name: {{ name|lower }}-split
  version: {{ pyston_version }}

source:
  - url: https://github.com/pyston/pyston/archive/pyston_{{ pyston_version }}.tar.gz
    sha256: 2a099e8d931d1da65d9394036c489fa767f680704efb5aa47b629958c3847059
  # pyston-lite uses a preprocessing script from inside the LuaJIT repository (that is not
  # packaged as part of the luajit package), but only as a build tool (ie is not included
  # in the built artifacts).
  - url: https://github.com/LuaJIT/LuaJIT/archive/e2c312e0deb874aa5fa8ce502c08d87deb38e82f.tar.gz
    sha256: bff4764c19466def90667d2f7fcbd0781b8e62476b12105868f8e44babd03f8e
    folder: pyston/LuaJIT/

build:
  number: 5
  skip: True  # [not linux or py>310]

# In theory the requirements can/should be specified per-output, but in practice
# conda-build will produce a corrupt package if the compiler dependency is not
# additionally specified at this top scope. It is required to declare the
# compiler dependency both here and in the outputs: section as well; removing
# either will cause the c compiler to not be installed.
#
# It's also required to specify a "python" dependency in this section so that
# conda-build knows that this package is sensitive to the python version.
# (It does not infer this from the py!=38 jinja selector)
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python

outputs:
  - name: pyston_lite
    # This 'script' line must go under 'outputs', not 'build'
    script: build_pyston_lite.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make
      host:
        - python
      run:
        - python

    test:
      imports:
        - pyston

  - name: pyston_lite_autoload
    build:
      # This 'script' line must go under 'build', not 'outputs'
      script: cd pyston/pyston_lite/autoload; PYSTON_LITE_NAME=pyston python setup.py install -v
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pyston_lite', exact=True) }}

    test:
      commands:
        - python -c "import sys; assert 'pyston' in sys.modules"

about:
  home: https://github.com/pyston/pyston
  summary: 'A JIT for Python'
  description: |
      pyston-lite is the JIT component of Pyston, a faster implementation of Python.
  license: PSF-2.0
  license_file: LICENSE

extra:
  feedstock-name: pyston_lite
  recipe-maintainers:
    - borchero
    - kmod
    - undingen
